from .api_views import (
    api_app_cola_contexto,
    api_app_estado,
    api_app_referencia_tiempo,
    api_buscar_vehiculo_por_codigo,
    api_despachador_mapa,
    api_escanear_qr,
    api_gps,
    api_gps_conductor,
    api_heartbeat,
    api_panel_frecuencia,
    api_paradas_vehiculo,
    api_puntos_control,
    api_recorrido_vehiculo,
    debug_gps,
)
from .auth_views import LoginSistemaView
from .despacho_views import (
    asignar_hora_fija,
    auditoria_horas,
    buscar_unidad_panel,
    cambiar_intervalo_global,
    control_ruta,
    despachador_mapa,
    detalle_salida,
    es_despachador,
    exportar_excel,
    historial_salidas,
    historial_vehiculo,
    marcar_paso,
    marcar_siguiente_punto,
    marcar_siguiente_punto_auto,
    panel_despachador,
    panel_frecuencia,
    poner_en_cola,
    quitar_de_cola,
    recorrido_vehiculo,
    reporte_control,
    ver_qr_unidad,
    desbloquear_hora,
)
from .reportes_views import ranking_unidades, reporte_salidas_diarias

__all__ = [
    "LoginSistemaView",
    "api_app_cola_contexto",
    "api_app_estado",
    "api_app_referencia_tiempo",
    "api_buscar_vehiculo_por_codigo",
    "api_despachador_mapa",
    "api_escanear_qr",
    "api_gps",
    "api_gps_conductor",
    "api_heartbeat",
    "api_panel_frecuencia",
    "api_paradas_vehiculo",
    "api_puntos_control",
    "api_recorrido_vehiculo",
    "asignar_hora_fija",
    "auditoria_horas",
    "buscar_unidad_panel",
    "cambiar_intervalo_global",
    "control_ruta",
    "debug_gps",
    "despachador_mapa",
    "detalle_salida",
    "es_despachador",
    "exportar_excel",
    "historial_salidas",
    "historial_vehiculo",
    "marcar_paso",
    "marcar_siguiente_punto",
    "marcar_siguiente_punto_auto",
    "panel_despachador",
    "panel_frecuencia",
    "poner_en_cola",
    "quitar_de_cola",
    "recorrido_vehiculo",
    "reporte_control",
    "ranking_unidades",
    "reporte_salidas_diarias",
    "ver_qr_unidad",
    "desbloquear_hora",
]


