# Generated by Django 4.2.7 on 2026-01-14 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_fijo', models.PositiveIntegerField(blank=True, help_text='Intervalo fijo en minutos. Vacío = automático', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_llegada', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('en_cola', models.BooleanField(default=False)),
                ('orden_cola', models.PositiveIntegerField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, help_text='Hora base de salida (referencia para puntos)', null=True)),
                ('hora_fija', models.DateTimeField(blank=True, null=True)),
                ('intervalo_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('bloqueado', models.BooleanField(default=False)),
                ('hora_real_salida', models.DateTimeField(blank=True, null=True)),
                ('diferencia_minutos', models.IntegerField(blank=True, help_text='Diferencia real vs programada (+/- minutos)', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código visible del vehículo (puede reutilizarse)', max_length=10)),
                ('placa', models.CharField(blank=True, help_text='Placa del vehículo (temporalmente permite vacío)', max_length=15, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el vehículo está activo en operación')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['codigo', 'activo'], name='flota_app_v_codigo_1d3c9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UbicacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('velocidad', models.FloatField(blank=True, help_text='Velocidad actual en km/h', null=True)),
                ('precision', models.FloatField(blank=True, help_text='Precisión GPS en metros', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_actual', to='flota_app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='SesionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Última señal de vida de la app del conductor', null=True)),
                ('salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='flota_app.registrosalida')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='flota_app.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='registrosalida',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota_app.ruta'),
        ),
        migrations.AddField(
            model_name='registrosalida',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota_app.vehiculo'),
        ),
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radio_metros', models.PositiveIntegerField(default=50)),
                ('orden', models.PositiveIntegerField()),
                ('offset_minutos', models.PositiveIntegerField(default=0, help_text='Minutos desde la hora de salida')),
                ('activo', models.BooleanField(default=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_control', to='flota_app.ruta')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('ruta', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='PosicionActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('velocidad', models.FloatField(default=0)),
                ('rumbo', models.FloatField(default=0)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posicion_actual', to='flota_app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='flota_app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='GPSRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(help_text='Latitud GPS')),
                ('lng', models.FloatField(help_text='Longitud GPS')),
                ('velocidad', models.FloatField(blank=True, help_text='Velocidad en km/h', null=True)),
                ('precision', models.FloatField(blank=True, help_text='Precisión GPS en metros', null=True)),
                ('bateria', models.IntegerField(blank=True, help_text='Nivel de batería del dispositivo (%)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_registros', to='flota_app.sesionunidad')),
            ],
            options={
                'verbose_name': 'Registro GPS',
                'verbose_name_plural': 'Registros GPS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MarcacionPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_programada', models.DateTimeField(blank=True, help_text='Hora programada calculada (hora salida + offset)', null=True)),
                ('hora_marcada', models.DateTimeField(blank=True, null=True)),
                ('diferencia_minutos', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('adelantado', 'Adelantado'), ('a_tiempo', 'A tiempo'), ('tarde', 'Tarde')], max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota_app.puntocontrol')),
                ('registro_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='flota_app.registrosalida')),
            ],
            options={
                'ordering': ['punto__orden'],
                'unique_together': {('registro_salida', 'punto')},
            },
        ),
    ]
