# Generated by Django 4.2.7 on 2026-01-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='es_prolongada',
            field=models.BooleanField(default=False, help_text='Indica si la parada superó el umbral de tiempo prolongado'),
        ),
    ]
