# Generated by Django 4.2.7 on 2026-01-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0002_parada_es_prolongada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosalida',
            name='diferencia_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrosalida',
            name='hora_salida',
            field=models.DateTimeField(blank=True, help_text='Hora base de salida (referencia para offsets)', null=True),
        ),
    ]
