# Generated by Django 4.2.7 on 2026-01-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0003_alter_registrosalida_diferencia_minutos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrosalida',
            options={'ordering': ['fecha', 'hora_salida']},
        ),
        migrations.AlterField(
            model_name='registrosalida',
            name='hora_real_salida',
            field=models.DateTimeField(blank=True, help_text='Momento real en que la unidad inició la salida', null=True),
        ),
        migrations.AddConstraint(
            model_name='registrosalida',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('vehiculo', 'fecha'), name='una_salida_activa_por_vehiculo_y_dia'),
        ),
    ]
