# Generated by Django 4.2.7 on 2026-01-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0004_alter_registrosalida_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrosalida',
            options={'ordering': ['fecha', 'creado_en']},
        ),
        migrations.AlterField(
            model_name='registrosalida',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota_app.ruta'),
        ),
    ]
