# Generated by Django 4.2.7 on 2026-01-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0005_alter_registrosalida_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacionpunto',
            name='audio_flag',
            field=models.CharField(blank=True, help_text='Audio que debe reproducir el App Conductor', max_length=50, null=True),
        ),
    ]
