# Generated by Django 4.2.7 on 2026-01-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0006_marcacionpunto_audio_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpsregistro',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='configuraciondespacho',
            name='intervalo_fijo',
            field=models.PositiveIntegerField(blank=True, help_text='Intervalo fijo en minutos (vacío = automático)', null=True),
        ),
        migrations.AlterField(
            model_name='gpsregistro',
            name='bateria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsregistro',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpsregistro',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpsregistro',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsregistro',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gpsregistro',
            name='velocidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marcacionpunto',
            name='audio_flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marcacionpunto',
            name='hora_programada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='es_prolongada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='puntocontrol',
            name='offset_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrosalida',
            name='hora_real_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrosalida',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesionunidad',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionvehiculo',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionvehiculo',
            name='velocidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='codigo',
            field=models.CharField(help_text='Código visible del vehículo (01, 02, 15, etc.)', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, help_text='Placa del vehículo', max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='PosicionActual',
        ),
    ]
