# Generated by Django 4.2.7 on 2026-02-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0007_alter_gpsregistro_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Mensaje mostrado en la app (debajo de Punto actual)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la que se muestra el mensaje')),
                ('fecha_fin', models.DateField(help_text='Fecha hasta la que se muestra el mensaje')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
