# Generated by Django 4.2.7 on 2026-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0008_mensajeglobal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajeglobal',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AddField(
            model_name='mensajeglobal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última modificación del mensaje'),
        ),
        migrations.AlterField(
            model_name='mensajeglobal',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el mensaje está activo'),
        ),
        migrations.AlterField(
            model_name='mensajeglobal',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='mensajeglobal',
            name='texto',
            field=models.TextField(help_text='Mensaje mostrado en la app (barra roja superior)'),
        ),
    ]
