# Generated by Django 4.2.7 on 2026-02-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0009_alter_mensajeglobal_options_mensajeglobal_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeglobal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mensajeglobal',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mensajeglobal',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mensajeglobal',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mensajeglobal',
            name='texto',
            field=models.TextField(help_text='Mensaje mostrado en la app'),
        ),
    ]
