# Generated by Django 4.2.7 on 2026-03-17 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0012_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciondespacho',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='flota_app.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='flota_app.empresa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('empresa', 'nombre')},
        ),
    ]
