# Generated by Django 4.2.7 on 2026-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0013_configuraciondespacho_empresa_ruta_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehiculo',
            name='flota_app_v_codigo_1d3c9a_idx',
        ),
        migrations.AddIndex(
            model_name='gpsregistro',
            index=models.Index(fields=['sesion', 'timestamp'], name='flota_app_g_sesion__60915b_idx'),
        ),
        migrations.AddIndex(
            model_name='parada',
            index=models.Index(fields=['vehiculo', 'inicio'], name='flota_app_p_vehicul_2b5030_idx'),
        ),
        migrations.AddIndex(
            model_name='parada',
            index=models.Index(fields=['activa'], name='flota_app_p_activa_040b20_idx'),
        ),
        migrations.AddIndex(
            model_name='registrosalida',
            index=models.Index(fields=['fecha', 'activo'], name='flota_app_r_fecha_3c00bc_idx'),
        ),
        migrations.AddIndex(
            model_name='registrosalida',
            index=models.Index(fields=['vehiculo', 'fecha'], name='flota_app_r_vehicul_5a6acc_idx'),
        ),
        migrations.AddIndex(
            model_name='registrosalida',
            index=models.Index(fields=['ruta', 'fecha'], name='flota_app_r_ruta_id_9c282f_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['empresa'], name='flota_app_r_empresa_1f7af2_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacionvehiculo',
            index=models.Index(fields=['updated_at'], name='flota_app_u_updated_9b2284_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['empresa', 'codigo'], name='flota_app_v_empresa_8eb39e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['empresa', 'activo'], name='flota_app_v_empresa_136f4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='configuraciondespacho',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('empresa',), name='una_config_activa_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empresa', 'codigo'), name='unique_codigo_activo_por_empresa'),
        ),
    ]
