# Generated by Django 4.2.7 on 2026-03-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0014_remove_vehiculo_flota_app_v_codigo_1d3c9a_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registrosalida',
            index=models.Index(fields=['vehiculo', 'activo'], name='flota_app_r_vehicul_eced5b_idx'),
        ),
    ]
