# Generated by Django 4.2.7 on 2026-03-31 19:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0016_ruta_geometria'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gpsregistro',
            name='flota_app_g_sesion__60915b_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrosalida',
            name='flota_app_r_fecha_3c00bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrosalida',
            name='flota_app_r_vehicul_5a6acc_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrosalida',
            name='flota_app_r_ruta_id_9c282f_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrosalida',
            name='flota_app_r_vehicul_eced5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='ruta',
            name='flota_app_r_empresa_1f7af2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='puntocontrol',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='configuraciondespacho',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gpsregistro',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sesionunidad',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='sesionunidad',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesionunidad',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='flota_app.empresa'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='configuraciondespacho',
            index=models.Index(fields=['empresa', 'activa'], name='flota_app_c_empresa_26d68e_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['ruc'], name='flota_app_e_ruc_3bb676_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsregistro',
            index=models.Index(fields=['sesion', '-timestamp'], name='flota_app_g_sesion__632754_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsregistro',
            index=models.Index(fields=['-timestamp'], name='flota_app_g_timesta_e8c576_idx'),
        ),
        migrations.AddIndex(
            model_name='marcacionpunto',
            index=models.Index(fields=['registro_salida', 'hora_marcada'], name='flota_app_m_registr_bfc49c_idx'),
        ),
        migrations.AddIndex(
            model_name='marcacionpunto',
            index=models.Index(fields=['punto'], name='flota_app_m_punto_i_dbf89f_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeglobal',
            index=models.Index(fields=['activo', 'fecha_inicio', 'fecha_fin'], name='flota_app_m_activo_1b1c49_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeglobal',
            index=models.Index(fields=['activo'], name='flota_app_m_activo_6d9aab_idx'),
        ),
        migrations.AddIndex(
            model_name='parada',
            index=models.Index(fields=['vehiculo', 'activa'], name='flota_app_p_vehicul_22d287_idx'),
        ),
        migrations.AddIndex(
            model_name='puntocontrol',
            index=models.Index(fields=['ruta', 'activo'], name='flota_app_p_ruta_id_af5b73_idx'),
        ),
        migrations.AddIndex(
            model_name='puntocontrol',
            index=models.Index(fields=['ruta', 'orden'], name='flota_app_p_ruta_id_34ae6f_idx'),
        ),
        migrations.AddIndex(
            model_name='registrosalida',
            index=models.Index(fields=['vehiculo', 'fecha', 'activo', 'en_cola'], name='flota_app_r_vehicul_de37af_idx'),
        ),
        migrations.AddIndex(
            model_name='registrosalida',
            index=models.Index(fields=['ruta', 'fecha', 'en_cola', 'orden_cola'], name='flota_app_r_ruta_id_898f41_idx'),
        ),
        migrations.AddIndex(
            model_name='registrosalida',
            index=models.Index(fields=['en_cola', 'orden_cola'], name='flota_app_r_en_cola_ff5ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['empresa', 'nombre'], name='flota_app_r_empresa_22816c_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionunidad',
            index=models.Index(fields=['vehiculo', 'activa'], name='flota_app_s_vehicul_5e4a74_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionunidad',
            index=models.Index(fields=['token', 'activa'], name='flota_app_s_token_05d0df_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionunidad',
            index=models.Index(fields=['expira_en'], name='flota_app_s_expira__7d8be3_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionunidad',
            index=models.Index(fields=['last_heartbeat'], name='flota_app_s_last_he_6b274d_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacionvehiculo',
            index=models.Index(fields=['vehiculo', 'updated_at'], name='flota_app_u_vehicul_78704c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['activo'], name='flota_app_v_activo_bf8647_idx'),
        ),
        migrations.AddConstraint(
            model_name='puntocontrol',
            constraint=models.UniqueConstraint(fields=('ruta', 'orden'), name='unique_ruta_orden'),
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='unique_ruta_empresa_nombre'),
        ),
    ]
