# Generated by Django 4.2.7 on 2026-04-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0017_remove_gpsregistro_flota_app_g_sesion__60915b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeglobal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_globales', to='flota_app.empresa'),
        ),
        migrations.AddIndex(
            model_name='mensajeglobal',
            index=models.Index(fields=['empresa', 'activo', 'fecha_inicio', 'fecha_fin'], name='flota_app_m_empresa_42220f_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesionunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('vehiculo',), name='una_sesion_activa_por_vehiculo'),
        ),
    ]
