# Generated by Django 4.2.7 on 2026-04-16 03:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0020_sesionstaffapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], db_index=True, max_length=10)),
                ('categoria', models.CharField(db_index=True, default='Otros', max_length=60)),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_operacion', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-fecha_operacion', '-creado_en', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='sesionstaffapp',
            new_name='flota_app_s_user_id_107056_idx',
            old_name='flota_app_s_user_ac_b4d52b_idx',
        ),
        migrations.RenameIndex(
            model_name='sesionstaffapp',
            new_name='flota_app_s_empresa_111b6d_idx',
            old_name='flota_app_s_empresa_84584b_idx',
        ),
        migrations.RenameIndex(
            model_name='sesionstaffapp',
            new_name='flota_app_s_token_3477b5_idx',
            old_name='flota_app_s_token_3be5b0_idx',
        ),
        migrations.RenameIndex(
            model_name='sesionstaffapp',
            new_name='flota_app_s_expira__7046aa_idx',
            old_name='flota_app_s_expira_e6da82_idx',
        ),
        migrations.RenameIndex(
            model_name='sesionstaffapp',
            new_name='flota_app_s_ultimo__d97121_idx',
            old_name='flota_app_s_ultimo__f7e69f_idx',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='flota_app.empresa'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='flota_app.registrosalida'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='flota_app.sesionunidad'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='flota_app.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['empresa', 'vehiculo', 'fecha_operacion'], name='flota_app_m_empresa_18a847_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['vehiculo', 'tipo', 'fecha_operacion'], name='flota_app_m_vehicul_dd01ff_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['sesion', 'fecha_operacion'], name='flota_app_m_sesion__5b8301_idx'),
        ),
    ]
