# Generated by Django 4.2.7 on 2026-04-16 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0021_movimientocaja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeglobal',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_directos', to='flota_app.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='mensajeglobal',
            index=models.Index(fields=['vehiculo', 'activo', 'fecha_inicio', 'fecha_fin'], name='flota_app_m_vehicul_9ccbf4_idx'),
        ),
    ]
