# Generated by Django 4.2.7 on 2026-05-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota_app", "0022_mensajeglobal_vehiculo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ubicacionvehiculo",
            name="ultimo_punto_evento_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ubicacionvehiculo",
            name="ultimo_punto_evento_codigo",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ubicacionvehiculo",
            name="ultimo_punto_evento_orden",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
