# Generated by Django 4.2.7 on 2026-05-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota_app", "0023_ubicacionvehiculo_ultimo_punto_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="puntocontrol",
            name="es_contexto_interno",
            field=models.BooleanField(
                default=False,
                help_text="Oculta este punto de la UI y lo usa solo para logica interna.",
            ),
        ),
        migrations.AddField(
            model_name="ubicacionvehiculo",
            name="en_retorno",
            field=models.BooleanField(default=False),
        ),
    ]
