# Generated by Django 4.2.7 on 2026-05-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0024_puntocontrol_es_contexto_interno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacionpunto',
            name='estado',
            field=models.CharField(blank=True, choices=[('adelantado', 'Adelantado'), ('a_tiempo', 'A tiempo'), ('tarde', 'Tarde'), ('omitido', 'Omitido')], max_length=20, null=True),
        ),
    ]
