# Generated by Django 4.2.7 on 2026-05-18 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0027_puntocontrol_confirma_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosco_activo', models.BooleanField(db_index=True, default=False)),
                ('pantalla_fija_activa', models.BooleanField(default=False)),
                ('wifi_conectado', models.BooleanField(db_index=True, default=False)),
                ('wifi_ssid', models.CharField(blank=True, default='', max_length=100)),
                ('internet_disponible', models.BooleanField(db_index=True, default=False)),
                ('gps_activo', models.BooleanField(db_index=True, default=False)),
                ('bateria_porcentaje', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip_local', models.GenericIPAddressField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('app_version_code', models.CharField(blank=True, default='', max_length=30)),
                ('android_version', models.CharField(blank=True, default='', max_length=30)),
                ('device_model', models.CharField(blank=True, default='', max_length=80)),
                ('ultimo_reinicio_en', models.DateTimeField(blank=True, null=True)),
                ('reportado_en', models.DateTimeField(auto_now=True, db_index=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_dispositivo', to='flota_app.vehiculo')),
            ],
            options={
                'verbose_name': 'Estado del dispositivo',
                'verbose_name_plural': 'Estados de dispositivos',
                'indexes': [models.Index(fields=['reportado_en'], name='flota_app_e_reporta_8a420a_idx'), models.Index(fields=['vehiculo', 'reportado_en'], name='flota_app_e_vehicul_5822bf_idx'), models.Index(fields=['kiosco_activo', 'reportado_en'], name='flota_app_e_kiosco__cb623f_idx'), models.Index(fields=['wifi_conectado', 'internet_disponible'], name='flota_app_e_wifi_co_655a9a_idx')],
            },
        ),
    ]
