# Generated by Django 4.2.7 on 2026-05-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flota_app', '0028_estadodispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FORZAR_SYNC', 'Forzar sincronizacion'), ('REPORTAR_ESTADO', 'Reportar estado'), ('REABRIR_APP', 'Reabrir app'), ('ACTIVAR_KIOSCO', 'Activar kiosco'), ('SALIR_KIOSCO', 'Salir kiosco'), ('ABRIR_WIFI_TECNICO', 'Abrir WiFi tecnico')], db_index=True, max_length=40)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('APLICADO', 'Aplicado'), ('ERROR', 'Error'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('detalle_error', models.TextField(blank=True, default='')),
                ('solicitado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos_dispositivo', to='flota_app.vehiculo')),
            ],
            options={
                'verbose_name': 'Comando del dispositivo',
                'verbose_name_plural': 'Comandos de dispositivos',
                'ordering': ['estado', '-solicitado_en', '-id'],
                'indexes': [models.Index(fields=['vehiculo', 'estado', '-solicitado_en'], name='flota_app_c_vehicul_9b2615_idx'), models.Index(fields=['estado', '-solicitado_en'], name='flota_app_c_estado_6abc59_idx'), models.Index(fields=['tipo', 'estado'], name='flota_app_c_tipo_032203_idx')],
            },
        ),
    ]
